### ISSUE TITLE
Prometheus metrics endpoint for scraping

### ISSUE THREAD

**Issue by Cottand** [Cottand/grimd#3]
This issue tracks a feature to add a `/metrics` endpoint to be able to scrape metrics

**Comment by tpaulus** [comment]
Proposed in https://github.com/looterz/grimd/pull/116

**Comment by Cottand** [comment]
Hey @tpaulus I also have an open PR there https://github.com/looterz/grimd/pull/115 since late August, but it does not seem the maintainer is very active. I am keen on keeping grimd maintained.

I added a few metrics to this fork [here](https://github.com/Cottand/grimd/blob/master/internal/metric/metric.go) (but not blocklist size like you did for example), as well as some other improvements (ARM builds).

Would you like to submit your PR to this repo and perhaps keep grimd alive in this fork? Let me know if you are eager on maintaining grimd as well, maybe between both of us we can bring it back up to speed and fix some of the issues on the original repo too
